// Auto-generated by scripts/write-build-info.mjs — do not edit
export const BUILD_TIME_ISO: string = "2026-04-01T15:45:11.271Z";
export const APP_VERSION: string = "1.0.3";
export const BUILD_DATE_DISPLAY: string = "1.4.2026";
export const BUILD_TIME_DISPLAY: string = "18.45.11";
