// Auto-generated by scripts/write-build-info.mjs — do not edit
export const BUILD_TIME_ISO: string = "2026-04-04T21:17:23.306Z";
export const APP_VERSION: string = "1.0.3";
export const BUILD_DATE_DISPLAY: string = "5.4.2026";
export const BUILD_TIME_DISPLAY: string = "00.17.23";
export const BUILD_DISPLAY_LINE: string = "5.4.2026 · 00.17.23";
