/**
 * Liikepankin luokitus — yksi id → yksi metatietue (V1 konservatiivinen).
 */
import { ALL_EXERCISES } from "@/lib/training/exercises";
import type { Exercise } from "@/types/exercise";
import type { ExerciseClassification } from "@/types/exerciseClassification";

const DEFAULT: ExerciseClassification = {
  movementPattern: "horizontal_push",
  trainingClass: "isolation",
  fatigueCost: "medium",
  beginnerFriendly: true,
  modality: "cable",
  rotationGroup: "generic",
  recoveryDemand: "medium",
  suitableForDropset: true,
  suitableForRestPause: true,
  suitableForHighRepPump: true,
};

const BY_ID: Record<string, ExerciseClassification> = {
  bench_press: {
    movementPattern: "horizontal_push",
    trainingClass: "compound_strength",
    fatigueCost: "high",
    beginnerFriendly: false,
    modality: "free_weight",
    rotationGroup: "horizontal_push_bar",
    recoveryDemand: "high",
    suitableForDropset: false,
    suitableForRestPause: false,
    suitableForHighRepPump: false,
  },
  dumbbell_flat_press: {
    movementPattern: "horizontal_push",
    trainingClass: "compound_hypertrophy",
    fatigueCost: "medium",
    beginnerFriendly: true,
    modality: "free_weight",
    rotationGroup: "horizontal_push_db",
    recoveryDemand: "medium",
    suitableForDropset: false,
    suitableForRestPause: true,
    suitableForHighRepPump: true,
  },
  incline_db_press: {
    movementPattern: "horizontal_push",
    trainingClass: "compound_hypertrophy",
    fatigueCost: "medium",
    beginnerFriendly: true,
    modality: "free_weight",
    rotationGroup: "incline_press",
    recoveryDemand: "medium",
    suitableForDropset: false,
    suitableForRestPause: true,
    suitableForHighRepPump: true,
  },
  ohp: {
    movementPattern: "vertical_push",
    trainingClass: "compound_strength",
    fatigueCost: "high",
    beginnerFriendly: false,
    modality: "free_weight",
    rotationGroup: "ohp",
    recoveryDemand: "high",
    suitableForDropset: false,
    suitableForRestPause: false,
    suitableForHighRepPump: false,
  },
  lateral_raise: {
    movementPattern: "vertical_push",
    trainingClass: "isolation",
    fatigueCost: "low",
    beginnerFriendly: true,
    modality: "free_weight",
    rotationGroup: "side_delts",
    recoveryDemand: "low",
    suitableForDropset: true,
    suitableForRestPause: true,
    suitableForHighRepPump: true,
  },
  tricep_pushdown: {
    movementPattern: "horizontal_push",
    trainingClass: "isolation",
    fatigueCost: "low",
    beginnerFriendly: true,
    modality: "cable",
    rotationGroup: "triceps_iso",
    recoveryDemand: "low",
    suitableForDropset: true,
    suitableForRestPause: true,
    suitableForHighRepPump: true,
  },
  skullcrusher: {
    movementPattern: "horizontal_push",
    trainingClass: "isolation",
    fatigueCost: "medium",
    beginnerFriendly: false,
    modality: "free_weight",
    rotationGroup: "triceps_iso",
    recoveryDemand: "medium",
    suitableForDropset: true,
    suitableForRestPause: true,
    suitableForHighRepPump: true,
  },
  close_grip_bench: {
    movementPattern: "horizontal_push",
    trainingClass: "compound_hypertrophy",
    fatigueCost: "medium",
    beginnerFriendly: false,
    modality: "free_weight",
    rotationGroup: "cgb",
    recoveryDemand: "medium",
    suitableForDropset: false,
    suitableForRestPause: true,
    suitableForHighRepPump: false,
  },
  dip: {
    movementPattern: "vertical_push",
    trainingClass: "compound_hypertrophy",
    fatigueCost: "medium",
    beginnerFriendly: true,
    modality: "bodyweight",
    rotationGroup: "dip",
    recoveryDemand: "medium",
    suitableForDropset: false,
    suitableForRestPause: true,
    suitableForHighRepPump: true,
  },
  cable_fly: {
    movementPattern: "horizontal_push",
    trainingClass: "isolation",
    fatigueCost: "low",
    beginnerFriendly: true,
    modality: "cable",
    rotationGroup: "chest_iso",
    recoveryDemand: "low",
    suitableForDropset: true,
    suitableForRestPause: true,
    suitableForHighRepPump: true,
  },
  lat_pulldown: {
    movementPattern: "vertical_pull",
    trainingClass: "machine_hypertrophy",
    fatigueCost: "medium",
    beginnerFriendly: true,
    modality: "machine",
    rotationGroup: "lat_pulldown",
    recoveryDemand: "medium",
    suitableForDropset: true,
    suitableForRestPause: true,
    suitableForHighRepPump: true,
  },
  pull_up: {
    movementPattern: "vertical_pull",
    trainingClass: "compound_hypertrophy",
    fatigueCost: "medium",
    beginnerFriendly: false,
    modality: "bodyweight",
    rotationGroup: "pull_up",
    recoveryDemand: "medium",
    suitableForDropset: false,
    suitableForRestPause: true,
    suitableForHighRepPump: true,
  },
  barbell_row: {
    movementPattern: "horizontal_pull",
    trainingClass: "compound_strength",
    fatigueCost: "high",
    beginnerFriendly: false,
    modality: "free_weight",
    rotationGroup: "barbell_row",
    recoveryDemand: "high",
    suitableForDropset: false,
    suitableForRestPause: false,
    suitableForHighRepPump: false,
  },
  dumbbell_row: {
    movementPattern: "horizontal_pull",
    trainingClass: "compound_hypertrophy",
    fatigueCost: "medium",
    beginnerFriendly: true,
    modality: "free_weight",
    rotationGroup: "db_row",
    recoveryDemand: "medium",
    suitableForDropset: false,
    suitableForRestPause: true,
    suitableForHighRepPump: true,
  },
  seated_cable_row: {
    movementPattern: "horizontal_pull",
    trainingClass: "machine_hypertrophy",
    fatigueCost: "medium",
    beginnerFriendly: true,
    modality: "cable",
    rotationGroup: "seated_row",
    recoveryDemand: "medium",
    suitableForDropset: true,
    suitableForRestPause: true,
    suitableForHighRepPump: true,
  },
  face_pull: {
    movementPattern: "horizontal_pull",
    trainingClass: "isolation",
    fatigueCost: "low",
    beginnerFriendly: true,
    modality: "cable",
    rotationGroup: "rear_delts",
    recoveryDemand: "low",
    suitableForDropset: true,
    suitableForRestPause: true,
    suitableForHighRepPump: true,
  },
  barbell_curl: {
    movementPattern: "horizontal_pull",
    trainingClass: "isolation",
    fatigueCost: "low",
    beginnerFriendly: true,
    modality: "free_weight",
    rotationGroup: "biceps",
    recoveryDemand: "low",
    suitableForDropset: true,
    suitableForRestPause: true,
    suitableForHighRepPump: true,
  },
  hammer_curl: {
    movementPattern: "horizontal_pull",
    trainingClass: "isolation",
    fatigueCost: "low",
    beginnerFriendly: true,
    modality: "free_weight",
    rotationGroup: "biceps",
    recoveryDemand: "low",
    suitableForDropset: true,
    suitableForRestPause: true,
    suitableForHighRepPump: true,
  },
  t_bar_row: {
    movementPattern: "horizontal_pull",
    trainingClass: "compound_hypertrophy",
    fatigueCost: "medium",
    beginnerFriendly: false,
    modality: "free_weight",
    rotationGroup: "t_bar",
    recoveryDemand: "medium",
    suitableForDropset: false,
    suitableForRestPause: true,
    suitableForHighRepPump: false,
  },
  back_squat: {
    movementPattern: "squat",
    trainingClass: "compound_strength",
    fatigueCost: "high",
    beginnerFriendly: false,
    modality: "free_weight",
    rotationGroup: "squat",
    recoveryDemand: "high",
    suitableForDropset: false,
    suitableForRestPause: false,
    suitableForHighRepPump: false,
  },
  smith_squat: {
    movementPattern: "squat",
    trainingClass: "compound_hypertrophy",
    fatigueCost: "medium",
    beginnerFriendly: true,
    modality: "machine",
    rotationGroup: "squat",
    recoveryDemand: "medium",
    suitableForDropset: false,
    suitableForRestPause: false,
    suitableForHighRepPump: false,
  },
  hack_squat: {
    movementPattern: "squat",
    trainingClass: "machine_hypertrophy",
    fatigueCost: "medium",
    beginnerFriendly: true,
    modality: "machine",
    rotationGroup: "squat",
    recoveryDemand: "medium",
    suitableForDropset: false,
    suitableForRestPause: true,
    suitableForHighRepPump: true,
  },
  leg_press: {
    movementPattern: "squat",
    trainingClass: "machine_hypertrophy",
    fatigueCost: "medium",
    beginnerFriendly: true,
    modality: "machine",
    rotationGroup: "leg_press",
    recoveryDemand: "medium",
    suitableForDropset: true,
    suitableForRestPause: true,
    suitableForHighRepPump: true,
  },
  lunge: {
    movementPattern: "lunge",
    trainingClass: "compound_hypertrophy",
    fatigueCost: "medium",
    beginnerFriendly: true,
    modality: "free_weight",
    rotationGroup: "lunge",
    recoveryDemand: "medium",
    suitableForDropset: false,
    suitableForRestPause: true,
    suitableForHighRepPump: true,
  },
  bulgarian_split_squat: {
    movementPattern: "lunge",
    trainingClass: "compound_hypertrophy",
    fatigueCost: "medium",
    beginnerFriendly: true,
    modality: "free_weight",
    rotationGroup: "bss",
    recoveryDemand: "medium",
    suitableForDropset: false,
    suitableForRestPause: true,
    suitableForHighRepPump: true,
  },
  leg_extension: {
    movementPattern: "squat",
    trainingClass: "isolation",
    fatigueCost: "low",
    beginnerFriendly: true,
    modality: "machine",
    rotationGroup: "quads_iso",
    recoveryDemand: "low",
    suitableForDropset: true,
    suitableForRestPause: true,
    suitableForHighRepPump: true,
  },
  leg_curl: {
    movementPattern: "hinge",
    trainingClass: "isolation",
    fatigueCost: "low",
    beginnerFriendly: true,
    modality: "machine",
    rotationGroup: "ham_iso",
    recoveryDemand: "low",
    suitableForDropset: true,
    suitableForRestPause: true,
    suitableForHighRepPump: true,
  },
  hip_thrust: {
    movementPattern: "hinge",
    trainingClass: "compound_hypertrophy",
    fatigueCost: "medium",
    beginnerFriendly: true,
    modality: "free_weight",
    rotationGroup: "hip_thrust",
    recoveryDemand: "medium",
    suitableForDropset: false,
    suitableForRestPause: true,
    suitableForHighRepPump: true,
  },
  rdl: {
    movementPattern: "hinge",
    trainingClass: "compound_strength",
    fatigueCost: "high",
    beginnerFriendly: false,
    modality: "free_weight",
    rotationGroup: "rdl",
    recoveryDemand: "high",
    suitableForDropset: false,
    suitableForRestPause: false,
    suitableForHighRepPump: false,
  },
  calf_standing: {
    movementPattern: "squat",
    trainingClass: "isolation",
    fatigueCost: "low",
    beginnerFriendly: true,
    modality: "machine",
    rotationGroup: "calf",
    recoveryDemand: "low",
    suitableForDropset: true,
    suitableForRestPause: true,
    suitableForHighRepPump: true,
  },
  calf_seated: {
    movementPattern: "squat",
    trainingClass: "isolation",
    fatigueCost: "low",
    beginnerFriendly: true,
    modality: "machine",
    rotationGroup: "calf",
    recoveryDemand: "low",
    suitableForDropset: true,
    suitableForRestPause: true,
    suitableForHighRepPump: true,
  },
  hanging_leg_raise: {
    movementPattern: "core",
    trainingClass: "accessory",
    fatigueCost: "low",
    beginnerFriendly: false,
    modality: "bodyweight",
    rotationGroup: "core_hang",
    recoveryDemand: "low",
    suitableForDropset: false,
    suitableForRestPause: true,
    suitableForHighRepPump: true,
  },
  cable_crunch: {
    movementPattern: "core",
    trainingClass: "isolation",
    fatigueCost: "low",
    beginnerFriendly: true,
    modality: "cable",
    rotationGroup: "core_iso",
    recoveryDemand: "low",
    suitableForDropset: true,
    suitableForRestPause: true,
    suitableForHighRepPump: true,
  },
  plank: {
    movementPattern: "core",
    trainingClass: "accessory",
    fatigueCost: "low",
    beginnerFriendly: true,
    modality: "bodyweight",
    rotationGroup: "plank",
    recoveryDemand: "low",
    suitableForDropset: false,
    suitableForRestPause: false,
    suitableForHighRepPump: false,
  },
  ab_wheel: {
    movementPattern: "core",
    trainingClass: "accessory",
    fatigueCost: "medium",
    beginnerFriendly: false,
    modality: "bodyweight",
    rotationGroup: "ab_wheel",
    recoveryDemand: "medium",
    suitableForDropset: false,
    suitableForRestPause: false,
    suitableForHighRepPump: false,
  },
  sit_up: {
    movementPattern: "core",
    trainingClass: "accessory",
    fatigueCost: "low",
    beginnerFriendly: true,
    modality: "bodyweight",
    rotationGroup: "situp",
    recoveryDemand: "low",
    suitableForDropset: false,
    suitableForRestPause: true,
    suitableForHighRepPump: true,
  },
  walk: {
    movementPattern: "conditioning",
    trainingClass: "conditioning_finisher",
    fatigueCost: "low",
    beginnerFriendly: true,
    modality: "bodyweight",
    rotationGroup: "cardio",
    recoveryDemand: "low",
    suitableForDropset: false,
    suitableForRestPause: false,
    suitableForHighRepPump: false,
  },
  bike: {
    movementPattern: "conditioning",
    trainingClass: "conditioning_finisher",
    fatigueCost: "medium",
    beginnerFriendly: true,
    modality: "machine",
    rotationGroup: "cardio",
    recoveryDemand: "medium",
    suitableForDropset: false,
    suitableForRestPause: false,
    suitableForHighRepPump: false,
  },
  elliptical: {
    movementPattern: "conditioning",
    trainingClass: "conditioning_finisher",
    fatigueCost: "medium",
    beginnerFriendly: true,
    modality: "machine",
    rotationGroup: "cardio",
    recoveryDemand: "medium",
    suitableForDropset: false,
    suitableForRestPause: false,
    suitableForHighRepPump: false,
  },
  stairs: {
    movementPattern: "conditioning",
    trainingClass: "conditioning_finisher",
    fatigueCost: "high",
    beginnerFriendly: true,
    modality: "machine",
    rotationGroup: "cardio",
    recoveryDemand: "high",
    suitableForDropset: false,
    suitableForRestPause: false,
    suitableForHighRepPump: false,
  },
};

export function classifyExercise(ex: Exercise): ExerciseClassification {
  return BY_ID[ex.id] ?? DEFAULT;
}

/** Yhteensopiva vanhan `inferMovementPattern`-kanssa (compound vs isolation). */
export function inferCompoundVsIsolation(ex: Exercise): "compound" | "isolation" {
  const c = classifyExercise(ex);
  if (
    c.trainingClass === "compound_strength" ||
    c.trainingClass === "compound_hypertrophy" ||
    c.trainingClass === "machine_hypertrophy" ||
    c.trainingClass === "skill_or_power"
  ) {
    return "compound";
  }
  if (c.trainingClass === "conditioning_finisher") return "compound";
  return "isolation";
}

export function knownExerciseIds(): string[] {
  return ALL_EXERCISES.map((e) => e.id);
}
