import type { GroceryStoreId, PricedCatalogProduct } from "@/types/grocery";

const S: Record<GroceryStoreId, GroceryStoreId> = {
  s_kaupat: "s_kaupat",
  prisma: "prisma",
  k_ruoka: "k_ruoka",
};

function row(p: PricedCatalogProduct): PricedCatalogProduct {
  return p;
}

/**
 * V1 käsin ylläpidetty katalogi: esimerkkihinnat €, ei reaaliaikaista API:a.
 * Kolme hintakerrosta vastaa S-ketjua / Prismaa / K-Ruokaa — ks. docs/GROCERY_RETAIL_V1.md
 */
export const RETAIL_GROCERY_CATALOG: PricedCatalogProduct[] = [
  // —— Kana ——
  row({
    id: "s_ch600",
    store: S.s_kaupat,
    name: "Broilerin filee",
    brand: "Kotimaista",
    category: "protein",
    unit: "pkt",
    sizeText: "600 g",
    priceEur: 5.29,
    pricePerUnitText: "8,82 €/kg",
    offerText: "−15 %",
    offerValidUntil: "2026-04-06",
    tags: ["kana", "filee"],
    matchesFoodKey: "chicken_breast",
    packSizeG: 600,
  }),
  row({
    id: "p_ch600",
    store: S.prisma,
    name: "Broilerin filee",
    category: "protein",
    unit: "pkt",
    sizeText: "600 g",
    priceEur: 5.99,
    pricePerUnitText: "9,98 €/kg",
    offerText: null,
    matchesFoodKey: "chicken_breast",
    packSizeG: 600,
  }),
  row({
    id: "k_ch600",
    store: S.k_ruoka,
    name: "Broilerin filee",
    brand: "Premium",
    category: "protein",
    unit: "pkt",
    sizeText: "600 g",
    priceEur: 6.49,
    pricePerUnitText: "10,82 €/kg",
    offerText: "K-plussa",
    offerValidUntil: "2026-04-10",
    matchesFoodKey: "chicken_breast",
    packSizeG: 600,
  }),
  row({
    id: "s_ch_strip",
    store: S.s_kaupat,
    name: "Broilerin fileesuikale",
    category: "protein",
    unit: "pkt",
    sizeText: "400 g",
    priceEur: 4.49,
    matchesFoodKey: "chicken_breast",
    packSizeG: 400,
  }),
  row({
    id: "p_ch_strip",
    store: S.prisma,
    name: "Broilerin fileesuikale",
    category: "protein",
    unit: "pkt",
    sizeText: "400 g",
    priceEur: 4.99,
    offerText: "2 pkt",
    offerValidUntil: "2026-04-05",
    matchesFoodKey: "chicken_breast",
    packSizeG: 400,
  }),
  row({
    id: "k_ch_strip",
    store: S.k_ruoka,
    name: "Broilerin fileesuikale",
    category: "protein",
    unit: "pkt",
    sizeText: "400 g",
    priceEur: 5.29,
    matchesFoodKey: "chicken_breast",
    packSizeG: 400,
  }),

  // —— Jauheliha ——
  row({
    id: "s_mince",
    store: S.s_kaupat,
    name: "Naudan jauheliha 17 %",
    category: "protein",
    unit: "pkt",
    sizeText: "400 g",
    priceEur: 5.79,
    matchesFoodKey: "beef_mince",
    packSizeG: 400,
  }),
  row({
    id: "p_mince",
    store: S.prisma,
    name: "Naudan jauheliha 17 %",
    category: "protein",
    unit: "pkt",
    sizeText: "400 g",
    priceEur: 6.19,
    offerText: "−10 %",
    offerValidUntil: "2026-04-07",
    matchesFoodKey: "beef_mince",
    packSizeG: 400,
  }),
  row({
    id: "k_mince",
    store: S.k_ruoka,
    name: "Naudan jauheliha 17 %",
    category: "protein",
    unit: "pkt",
    sizeText: "400 g",
    priceEur: 6.49,
    matchesFoodKey: "beef_mince",
    packSizeG: 400,
  }),

  // —— Lohi ——
  row({
    id: "s_salmon",
    store: S.s_kaupat,
    name: "Lohifilee",
    category: "protein",
    unit: "pkt",
    sizeText: "250 g",
    priceEur: 8.99,
    matchesFoodKey: "salmon",
    packSizeG: 250,
  }),
  row({
    id: "p_salmon",
    store: S.prisma,
    name: "Lohifilee",
    category: "protein",
    unit: "pkt",
    sizeText: "250 g",
    priceEur: 9.49,
    offerText: "Viikon kala",
    offerValidUntil: "2026-04-04",
    matchesFoodKey: "salmon",
    packSizeG: 250,
  }),
  row({
    id: "k_salmon",
    store: S.k_ruoka,
    name: "Lohifilee",
    category: "protein",
    unit: "pkt",
    sizeText: "250 g",
    priceEur: 9.99,
    matchesFoodKey: "salmon",
    packSizeG: 250,
  }),

  // —— Munat ——
  row({
    id: "s_eggs",
    store: S.s_kaupat,
    name: "Kananmunat M",
    category: "protein",
    unit: "rasia",
    sizeText: "10 kpl",
    priceEur: 2.69,
    matchesFoodKey: "eggs",
    packSizeG: 550,
  }),
  row({
    id: "p_eggs",
    store: S.prisma,
    name: "Kananmunat M",
    category: "protein",
    unit: "rasia",
    sizeText: "10 kpl",
    priceEur: 2.89,
    matchesFoodKey: "eggs",
    packSizeG: 550,
  }),
  row({
    id: "k_eggs",
    store: S.k_ruoka,
    name: "Kananmunat M",
    category: "protein",
    unit: "rasia",
    sizeText: "10 kpl",
    priceEur: 2.99,
    matchesFoodKey: "eggs",
    packSizeG: 550,
  }),

  // —— Riisi ——
  row({
    id: "s_rice",
    store: S.s_kaupat,
    name: "Pitkäjyväinen riisi",
    category: "carb",
    unit: "pkt",
    sizeText: "1 kg",
    priceEur: 2.19,
    matchesFoodKey: "rice",
    packSizeG: 1000,
  }),
  row({
    id: "p_rice",
    store: S.prisma,
    name: "Pitkäjyväinen riisi",
    category: "carb",
    unit: "pkt",
    sizeText: "1 kg",
    priceEur: 2.39,
    matchesFoodKey: "rice",
    packSizeG: 1000,
  }),
  row({
    id: "k_rice",
    store: S.k_ruoka,
    name: "Pitkäjyväinen riisi",
    category: "carb",
    unit: "pkt",
    sizeText: "1 kg",
    priceEur: 2.59,
    matchesFoodKey: "rice",
    packSizeG: 1000,
  }),

  // —— Kaura ——
  row({
    id: "s_oats",
    store: S.s_kaupat,
    name: "Kaurahiutaleet",
    category: "carb",
    unit: "pkt",
    sizeText: "1 kg",
    priceEur: 1.79,
    matchesFoodKey: "oats",
    packSizeG: 1000,
  }),
  row({
    id: "p_oats",
    store: S.prisma,
    name: "Kaurahiutaleet",
    category: "carb",
    unit: "pkt",
    sizeText: "1 kg",
    priceEur: 1.99,
    offerText: "2 pkt",
    offerValidUntil: "2026-04-08",
    matchesFoodKey: "oats",
    packSizeG: 1000,
  }),
  row({
    id: "k_oats",
    store: S.k_ruoka,
    name: "Kaurahiutaleet",
    category: "carb",
    unit: "pkt",
    sizeText: "1 kg",
    priceEur: 2.09,
    matchesFoodKey: "oats",
    packSizeG: 1000,
  }),

  // —— Peruna ——
  row({
    id: "s_pot",
    store: S.s_kaupat,
    name: "Peruna",
    category: "carb",
    unit: "pussi",
    sizeText: "2 kg",
    priceEur: 2.49,
    matchesFoodKey: "potato",
    packSizeG: 2000,
  }),
  row({
    id: "p_pot",
    store: S.prisma,
    name: "Peruna",
    category: "carb",
    unit: "pussi",
    sizeText: "2 kg",
    priceEur: 2.69,
    matchesFoodKey: "potato",
    packSizeG: 2000,
  }),
  row({
    id: "k_pot",
    store: S.k_ruoka,
    name: "Peruna",
    category: "carb",
    unit: "pussi",
    sizeText: "2 kg",
    priceEur: 2.89,
    matchesFoodKey: "potato",
    packSizeG: 2000,
  }),

  // —— Rahka ——
  row({
    id: "s_quark",
    store: S.s_kaupat,
    name: "Proteiinirahka",
    category: "dairy",
    unit: "rasia",
    sizeText: "200 g",
    priceEur: 1.29,
    matchesFoodKey: "quark",
    packSizeG: 200,
  }),
  row({
    id: "p_quark",
    store: S.prisma,
    name: "Proteiinirahka",
    category: "dairy",
    unit: "rasia",
    sizeText: "200 g",
    priceEur: 1.39,
    offerText: "3 rasia",
    offerValidUntil: "2026-04-09",
    matchesFoodKey: "quark",
    packSizeG: 200,
  }),
  row({
    id: "k_quark",
    store: S.k_ruoka,
    name: "Proteiinirahka",
    category: "dairy",
    unit: "rasia",
    sizeText: "200 g",
    priceEur: 1.49,
    matchesFoodKey: "quark",
    packSizeG: 200,
  }),

  // —— Raejuusto ——
  row({
    id: "s_cot",
    store: S.s_kaupat,
    name: "Raejuusto",
    category: "dairy",
    unit: "pkt",
    sizeText: "200 g",
    priceEur: 1.99,
    matchesFoodKey: "cottage_cheese",
    packSizeG: 200,
  }),
  row({
    id: "p_cot",
    store: S.prisma,
    name: "Raejuusto",
    category: "dairy",
    unit: "pkt",
    sizeText: "200 g",
    priceEur: 2.19,
    matchesFoodKey: "cottage_cheese",
    packSizeG: 200,
  }),
  row({
    id: "k_cot",
    store: S.k_ruoka,
    name: "Raejuusto",
    category: "dairy",
    unit: "pkt",
    sizeText: "200 g",
    priceEur: 2.29,
    matchesFoodKey: "cottage_cheese",
    packSizeG: 200,
  }),

  // —— Jogurtti ——
  row({
    id: "s_yog",
    store: S.s_kaupat,
    name: "Kreikkajogurtti",
    category: "dairy",
    unit: "purkki",
    sizeText: "400 g",
    priceEur: 2.49,
    matchesFoodKey: "yogurt",
    packSizeG: 400,
  }),
  row({
    id: "p_yog",
    store: S.prisma,
    name: "Kreikkajogurtti",
    category: "dairy",
    unit: "purkki",
    sizeText: "400 g",
    priceEur: 2.69,
    matchesFoodKey: "yogurt",
    packSizeG: 400,
  }),
  row({
    id: "k_yog",
    store: S.k_ruoka,
    name: "Kreikkajogurtti",
    category: "dairy",
    unit: "purkki",
    sizeText: "400 g",
    priceEur: 2.89,
    matchesFoodKey: "yogurt",
    packSizeG: 400,
  }),

  // —— Banaani ——
  row({
    id: "s_ban",
    store: S.s_kaupat,
    name: "Banaani",
    category: "fruit",
    unit: "kg",
    sizeText: "~1 kg",
    priceEur: 1.99,
    pricePerUnitText: "1,99 €/kg",
    matchesFoodKey: "banana",
    packSizeG: 1000,
  }),
  row({
    id: "p_ban",
    store: S.prisma,
    name: "Banaani",
    category: "fruit",
    unit: "kg",
    sizeText: "~1 kg",
    priceEur: 2.19,
    matchesFoodKey: "banana",
    packSizeG: 1000,
  }),
  row({
    id: "k_ban",
    store: S.k_ruoka,
    name: "Banaani",
    category: "fruit",
    unit: "kg",
    sizeText: "~1 kg",
    priceEur: 2.29,
    matchesFoodKey: "banana",
    packSizeG: 1000,
  }),

  // —— Marjat (berries key) ——
  row({
    id: "s_ber",
    store: S.s_kaupat,
    name: "Marjasekoitus pakaste",
    category: "fruit",
    unit: "pkt",
    sizeText: "500 g",
    priceEur: 3.49,
    matchesFoodKey: "berries",
    packSizeG: 500,
  }),
  row({
    id: "p_ber",
    store: S.prisma,
    name: "Marjasekoitus pakaste",
    category: "fruit",
    unit: "pkt",
    sizeText: "500 g",
    priceEur: 3.79,
    matchesFoodKey: "berries",
    packSizeG: 500,
  }),
  row({
    id: "k_ber",
    store: S.k_ruoka,
    name: "Marjasekoitus pakaste",
    category: "fruit",
    unit: "pkt",
    sizeText: "500 g",
    priceEur: 3.99,
    matchesFoodKey: "berries",
    packSizeG: 500,
  }),

  // —— Pakastevihannekset ——
  row({
    id: "s_fv",
    store: S.s_kaupat,
    name: "Wok-vihannekset pakaste",
    category: "vegetable",
    unit: "pkt",
    sizeText: "750 g",
    priceEur: 2.99,
    matchesFoodKey: "frozen_veg",
    packSizeG: 750,
  }),
  row({
    id: "p_fv",
    store: S.prisma,
    name: "Wok-vihannekset pakaste",
    category: "vegetable",
    unit: "pkt",
    sizeText: "750 g",
    priceEur: 3.19,
    offerText: "2 pkt",
    offerValidUntil: "2026-04-06",
    matchesFoodKey: "frozen_veg",
    packSizeG: 750,
  }),
  row({
    id: "k_fv",
    store: S.k_ruoka,
    name: "Wok-vihannekset pakaste",
    category: "vegetable",
    unit: "pkt",
    sizeText: "750 g",
    priceEur: 3.39,
    matchesFoodKey: "frozen_veg",
    packSizeG: 750,
  }),
  row({
    id: "s_vf",
    store: S.s_kaupat,
    name: "Parsakaali pakaste",
    category: "vegetable",
    unit: "pkt",
    sizeText: "450 g",
    priceEur: 2.29,
    matchesFoodKey: "veg_frozen",
    packSizeG: 450,
  }),

  // —— Salaatti ——
  row({
    id: "s_sg",
    store: S.s_kaupat,
    name: "Salaattisekoitus",
    category: "vegetable",
    unit: "pussi",
    sizeText: "150 g",
    priceEur: 1.99,
    matchesFoodKey: "salad_greens",
    packSizeG: 150,
  }),
  row({
    id: "p_sg",
    store: S.prisma,
    name: "Salaattisekoitus",
    category: "vegetable",
    unit: "pussi",
    sizeText: "150 g",
    priceEur: 2.19,
    matchesFoodKey: "salad_greens",
    packSizeG: 150,
  }),
  row({
    id: "k_sg",
    store: S.k_ruoka,
    name: "Salaattisekoitus",
    category: "vegetable",
    unit: "pussi",
    sizeText: "150 g",
    priceEur: 2.39,
    matchesFoodKey: "salad_greens",
    packSizeG: 150,
  }),

  // —— Oliiviöljy ——
  row({
    id: "s_oo",
    store: S.s_kaupat,
    name: "Oliiviöljy",
    category: "fat",
    unit: "pullo",
    sizeText: "500 ml",
    priceEur: 6.99,
    matchesFoodKey: "olive_oil",
    packSizeG: 500,
  }),
  row({
    id: "p_oo",
    store: S.prisma,
    name: "Oliiviöljy",
    category: "fat",
    unit: "pullo",
    sizeText: "500 ml",
    priceEur: 7.49,
    offerText: "−12 %",
    offerValidUntil: "2026-04-05",
    matchesFoodKey: "olive_oil",
    packSizeG: 500,
  }),
  row({
    id: "k_oo",
    store: S.k_ruoka,
    name: "Oliiviöljy",
    category: "fat",
    unit: "pullo",
    sizeText: "500 ml",
    priceEur: 7.99,
    matchesFoodKey: "olive_oil",
    packSizeG: 500,
  }),

  // —— Proteiinijuoma ——
  row({
    id: "s_ps",
    store: S.s_kaupat,
    name: "Proteiinijuoma",
    category: "drink",
    unit: "pullo",
    sizeText: "330 ml",
    priceEur: 2.49,
    matchesFoodKey: "protein_shake",
    packSizeG: 330,
  }),
  row({
    id: "p_ps",
    store: S.prisma,
    name: "Proteiinijuoma",
    category: "drink",
    unit: "pullo",
    sizeText: "330 ml",
    priceEur: 2.69,
    matchesFoodKey: "protein_shake",
    packSizeG: 330,
  }),
  row({
    id: "k_ps",
    store: S.k_ruoka,
    name: "Proteiinijuoma",
    category: "drink",
    unit: "pullo",
    sizeText: "330 ml",
    priceEur: 2.89,
    offerText: "4 pkt",
    offerValidUntil: "2026-04-07",
    matchesFoodKey: "protein_shake",
    packSizeG: 330,
  }),

  // —— Tortilla ——
  row({
    id: "s_tor",
    store: S.s_kaupat,
    name: "Tortillat",
    category: "carb",
    unit: "pkt",
    sizeText: "320 g / 8 kpl",
    priceEur: 2.19,
    matchesFoodKey: "tortilla",
    packSizeG: 320,
  }),
  row({
    id: "p_tor",
    store: S.prisma,
    name: "Tortillat",
    category: "carb",
    unit: "pkt",
    sizeText: "320 g",
    priceEur: 2.39,
    matchesFoodKey: "tortilla",
    packSizeG: 320,
  }),
  row({
    id: "k_tor",
    store: S.k_ruoka,
    name: "Tortillat",
    category: "carb",
    unit: "pkt",
    sizeText: "320 g",
    priceEur: 2.59,
    matchesFoodKey: "tortilla",
    packSizeG: 320,
  }),

  // —— Leipä ——
  row({
    id: "s_br",
    store: S.s_kaupat,
    name: "Täysjyväleipä",
    category: "carb",
    unit: "kpl",
    sizeText: "500 g",
    priceEur: 2.99,
    matchesFoodKey: "bread",
    packSizeG: 500,
  }),
  row({
    id: "p_br",
    store: S.prisma,
    name: "Täysjyväleipä",
    category: "carb",
    unit: "kpl",
    sizeText: "500 g",
    priceEur: 3.19,
    matchesFoodKey: "bread",
    packSizeG: 500,
  }),
  row({
    id: "k_br",
    store: S.k_ruoka,
    name: "Täysjyväleipä",
    category: "carb",
    unit: "kpl",
    sizeText: "500 g",
    priceEur: 3.39,
    matchesFoodKey: "bread",
    packSizeG: 500,
  }),

  // —— Pasta ——
  row({
    id: "s_pas",
    store: S.s_kaupat,
    name: "Pasta",
    category: "carb",
    unit: "pkt",
    sizeText: "500 g",
    priceEur: 1.19,
    matchesFoodKey: "pasta",
    packSizeG: 500,
  }),
  row({
    id: "p_pas",
    store: S.prisma,
    name: "Pasta",
    category: "carb",
    unit: "pkt",
    sizeText: "500 g",
    priceEur: 1.29,
    matchesFoodKey: "pasta",
    packSizeG: 500,
  }),
  row({
    id: "k_pas",
    store: S.k_ruoka,
    name: "Pasta",
    category: "carb",
    unit: "pkt",
    sizeText: "500 g",
    priceEur: 1.39,
    offerText: "2 pkt",
    offerValidUntil: "2026-04-08",
    matchesFoodKey: "pasta",
    packSizeG: 500,
  }),

  // —— Pähkinät ——
  row({
    id: "s_nut",
    store: S.s_kaupat,
    name: "Sekapähkinät",
    category: "snack",
    unit: "pussi",
    sizeText: "200 g",
    priceEur: 3.99,
    matchesFoodKey: "nuts",
    packSizeG: 200,
  }),
  row({
    id: "p_nut",
    store: S.prisma,
    name: "Sekapähkinät",
    category: "snack",
    unit: "pussi",
    sizeText: "200 g",
    priceEur: 4.29,
    matchesFoodKey: "nuts",
    packSizeG: 200,
  }),
  row({
    id: "k_nut",
    store: S.k_ruoka,
    name: "Sekapähkinät",
    category: "snack",
    unit: "pussi",
    sizeText: "200 g",
    priceEur: 4.49,
    matchesFoodKey: "nuts",
    packSizeG: 200,
  }),

  // —— Tofu ——
  row({
    id: "s_tofu",
    store: S.s_kaupat,
    name: "Tofu",
    category: "protein",
    unit: "pkt",
    sizeText: "250 g",
    priceEur: 2.99,
    matchesFoodKey: "tofu",
    packSizeG: 250,
  }),
  row({
    id: "p_tofu",
    store: S.prisma,
    name: "Tofu",
    category: "protein",
    unit: "pkt",
    sizeText: "250 g",
    priceEur: 3.19,
    matchesFoodKey: "tofu",
    packSizeG: 250,
  }),
  row({
    id: "k_tofu",
    store: S.k_ruoka,
    name: "Tofu",
    category: "protein",
    unit: "pkt",
    sizeText: "250 g",
    priceEur: 3.39,
    matchesFoodKey: "tofu",
    packSizeG: 250,
  }),
];

export function getRetailCatalog(): PricedCatalogProduct[] {
  return RETAIL_GROCERY_CATALOG;
}
