/**
 * Ruokarakenteiden kirjasto — blueprint + ateriarytmi; valinta lukitsee nutritionBlueprintId:n.
 */
import { resolveProgramFromProfile } from "@/lib/profileProgramResolver";
import type { NutritionLibraryEntry } from "@/types/nutritionLibrary";
import type { Goal, OnboardingAnswers } from "@/types/coach";

export const NUTRITION_LIBRARY: NutritionLibraryEntry[] = [
  {
    id: "easy_3_meals",
    nameFi: "3 ateriaa — helppo",
    nameEn: "3 meals — easy",
    goal: "any",
    mealsPerDay: 3,
    rhythmType: "three_easy",
    shortDescriptionFi: "Selkeä kolmijako, ei välipala stressiä.",
    shortDescriptionEn: "Clear three blocks, no snack stress.",
    idealForFi: "Säännöllinen arki.",
    idealForEn: "A regular week.",
    styleTag: "helppo",
    proteinBias: "standard",
    flexibilityLevel: "balanced",
    shiftCompatible: true,
    nutritionBlueprintId: "easy_daily",
    mealStructure: "three_meals",
  },
  {
    id: "normal_4_meals",
    nameFi: "4 ateriaa — tasapaino",
    nameEn: "4 meals — balance",
    goal: "any",
    mealsPerDay: 4,
    rhythmType: "four_normal",
    shortDescriptionFi: "Lounas ja välipala jakavat päivän.",
    shortDescriptionEn: "Lunch and snack split the day.",
    idealForFi: "Useimmat tavoitteet.",
    idealForEn: "Most goals.",
    styleTag: "normaali",
    proteinBias: "high",
    flexibilityLevel: "balanced",
    shiftCompatible: true,
    nutritionBlueprintId: "steady_meals",
    mealStructure: "snack_forward",
  },
  {
    id: "performance_5_meals",
    nameFi: "5 ateriaa — suoritus",
    nameEn: "5 meals — performance",
    goal: "build_muscle",
    mealsPerDay: 5,
    rhythmType: "five_performance",
    shortDescriptionFi: "Energia jakautuu koko päivään.",
    shortDescriptionEn: "Energy spread across the day.",
    idealForFi: "Kasvu ja isompi treenimäärä.",
    idealForEn: "Growth and higher training load.",
    styleTag: "suoritus",
    proteinBias: "very_high",
    flexibilityLevel: "structured",
    shiftCompatible: false,
    nutritionBlueprintId: "muscle_fuel",
    mealStructure: "snack_forward",
  },
  {
    id: "busy_day_meals",
    nameFi: "Kiire — minimi ateriat",
    nameEn: "Busy — minimal meals",
    goal: "any",
    mealsPerDay: 3,
    rhythmType: "busy",
    shortDescriptionFi: "Nopeat valinnat, ei monimutkaista.",
    shortDescriptionEn: "Fast choices, nothing fancy.",
    idealForFi: "Kiireinen viikko.",
    idealForEn: "A busy week.",
    styleTag: "kiire",
    proteinBias: "high",
    flexibilityLevel: "flex",
    shiftCompatible: true,
    nutritionBlueprintId: "easy_daily",
    mealStructure: "three_meals",
  },
  {
    id: "shift_work_structure",
    nameFi: "Vuorotyö — kellon mukaan",
    nameEn: "Shift work — clock-based",
    goal: "any",
    mealsPerDay: 4,
    rhythmType: "shift",
    shortDescriptionFi: "Ateriat seuraavat vuoroa, ei kello kahdeksaa.",
    shortDescriptionEn: "Meals follow the shift, not the clock.",
    idealForFi: "Vuorotyö tai epäsäännöllinen rytmi.",
    idealForEn: "Shift work or irregular rhythm.",
    styleTag: "vuoro",
    proteinBias: "high",
    flexibilityLevel: "flex",
    shiftCompatible: true,
    nutritionBlueprintId: "shift_clock",
    mealStructure: "snack_forward",
  },
  {
    id: "social_flex_structure",
    nameFi: "Sosiaalinen joustava",
    nameEn: "Social flex",
    goal: "any",
    mealsPerDay: 4,
    rhythmType: "social",
    shortDescriptionFi: "Tapahtumat mukana ilman romahdusta.",
    shortDescriptionEn: "Events included without losing the plot.",
    idealForFi: "Kun syöt usein ulkona.",
    idealForEn: "When you eat out often.",
    styleTag: "joustava",
    proteinBias: "standard",
    flexibilityLevel: "flex",
    shiftCompatible: true,
    nutritionBlueprintId: "event_balance",
    mealStructure: "snack_forward",
  },
  {
    id: "high_protein_cut",
    nameFi: "Korkea proteiini — kevennys",
    nameEn: "High protein — cut",
    goal: "lose_weight",
    mealsPerDay: 4,
    rhythmType: "cut",
    shortDescriptionFi: "Proteiini pitää nälän kurissa.",
    shortDescriptionEn: "Protein keeps hunger in check.",
    idealForFi: "Painonhallinta.",
    idealForEn: "Weight control.",
    styleTag: "cut",
    proteinBias: "very_high",
    flexibilityLevel: "balanced",
    shiftCompatible: true,
    nutritionBlueprintId: "light_cut_meal",
    mealStructure: "lighter_evening",
  },
  {
    id: "muscle_gain_meal_flow",
    nameFi: "Kasvu — ateriatreeni",
    nameEn: "Growth — meal flow",
    goal: "build_muscle",
    mealsPerDay: 4,
    rhythmType: "growth",
    shortDescriptionFi: "Riittävästi ennen ja jälkeen treenin.",
    shortDescriptionEn: "Enough before and after training.",
    idealForFi: "Lihaskasvu.",
    idealForEn: "Muscle gain.",
    styleTag: "kasvu",
    proteinBias: "very_high",
    flexibilityLevel: "structured",
    shiftCompatible: true,
    nutritionBlueprintId: "muscle_fuel",
    mealStructure: "snack_forward",
  },
  {
    id: "easy_3_meals_cut",
    nameFi: "3 ateriaa — kevennys",
    nameEn: "3 meals — cut",
    goal: "lose_weight",
    mealsPerDay: 3,
    rhythmType: "easy_3_cut",
    shortDescriptionFi: "Yksinkertainen kolmijako, proteiini edellä.",
    shortDescriptionEn: "Simple three-block day, protein first.",
    idealForFi: "Kun haluat vähemmän ateriapisteitä.",
    idealForEn: "When you want fewer meal moments.",
    styleTag: "cut",
    proteinBias: "high",
    flexibilityLevel: "balanced",
    shiftCompatible: true,
    nutritionBlueprintId: "light_cut_meal",
    mealStructure: "lighter_evening",
    tags: ["cut", "easy_3"],
  },
  {
    id: "easy_3_meals_growth",
    nameFi: "3 ateriaa — kasvu",
    nameEn: "3 meals — growth",
    goal: "build_muscle",
    mealsPerDay: 3,
    rhythmType: "easy_3_growth",
    shortDescriptionFi: "Isoja aterioita, selkeä rytmi.",
    shortDescriptionEn: "Bigger plates, clear rhythm.",
    idealForFi: "Kun välipaloja ei jakseta miettiä.",
    idealForEn: "When you do not want to think about snacks.",
    styleTag: "kasvu",
    proteinBias: "very_high",
    flexibilityLevel: "structured",
    shiftCompatible: true,
    nutritionBlueprintId: "muscle_fuel",
    mealStructure: "three_meals",
    tags: ["growth", "easy_3"],
  },
  {
    id: "normal_4_meals_cut",
    nameFi: "4 ateriaa — kevennys",
    nameEn: "4 meals — cut",
    goal: "lose_weight",
    mealsPerDay: 4,
    rhythmType: "normal_4_cut",
    shortDescriptionFi: "Välipala jakaa nälkää.",
    shortDescriptionEn: "A snack splits hunger.",
    idealForFi: "Kun päivä on pitkä mutta kontrolli säilyy.",
    idealForEn: "When the day is long but control stays.",
    styleTag: "cut",
    proteinBias: "high",
    flexibilityLevel: "balanced",
    shiftCompatible: true,
    nutritionBlueprintId: "light_cut_meal",
    mealStructure: "snack_forward",
    tags: ["cut", "normal_4"],
  },
  {
    id: "normal_4_meals_growth",
    nameFi: "4 ateriaa — kasvu",
    nameEn: "4 meals — growth",
    goal: "build_muscle",
    mealsPerDay: 4,
    rhythmType: "normal_4_growth",
    shortDescriptionFi: "Klassinen välipala tukemaan treeniä.",
    shortDescriptionEn: "Classic snack to support training.",
    idealForFi: "Kun kasvuvaiheessa tarvitaan tiheää energiaa.",
    idealForEn: "When growth needs steady energy.",
    styleTag: "kasvu",
    proteinBias: "very_high",
    flexibilityLevel: "structured",
    shiftCompatible: true,
    nutritionBlueprintId: "muscle_fuel",
    mealStructure: "snack_forward",
    tags: ["growth", "normal_4"],
  },
  {
    id: "busy_day_meals_cut",
    nameFi: "Kiire — kevennys",
    nameEn: "Busy — cut",
    goal: "lose_weight",
    mealsPerDay: 3,
    rhythmType: "busy_cut",
    shortDescriptionFi: "Nopeat valinnat, proteiini kohillaan.",
    shortDescriptionEn: "Fast picks, protein on point.",
    idealForFi: "Kun aikaa ei ole mutta linja pitää.",
    idealForEn: "When time is short but the line must hold.",
    styleTag: "kiire",
    proteinBias: "high",
    flexibilityLevel: "flex",
    shiftCompatible: true,
    nutritionBlueprintId: "easy_daily",
    mealStructure: "three_meals",
    tags: ["busy", "cut"],
  },
  {
    id: "busy_day_meals_growth",
    nameFi: "Kiire — kasvu",
    nameEn: "Busy — growth",
    goal: "build_muscle",
    mealsPerDay: 3,
    rhythmType: "busy_growth",
    shortDescriptionFi: "Minimiateriat, maksimiproteiini.",
    shortDescriptionEn: "Minimum meals, maximum protein density.",
    idealForFi: "Kun päivä on täynnä mutta treeni vaatii polttoainetta.",
    idealForEn: "When the day is packed but training needs fuel.",
    styleTag: "kiire",
    proteinBias: "very_high",
    flexibilityLevel: "flex",
    shiftCompatible: true,
    nutritionBlueprintId: "muscle_fuel",
    mealStructure: "three_meals",
    tags: ["busy", "growth"],
  },
  {
    id: "shift_work_structure_cut",
    nameFi: "Vuorotyö — kevennys",
    nameEn: "Shift work — cut",
    goal: "lose_weight",
    mealsPerDay: 4,
    rhythmType: "shift_cut",
    shortDescriptionFi: "Kello ei sanele ensimmäistä ateriaa.",
    shortDescriptionEn: "The clock does not rule the first meal.",
    idealForFi: "Vuorotyö ja painonhallinta yhtä aikaa.",
    idealForEn: "Shift work plus weight control.",
    styleTag: "vuoro",
    proteinBias: "high",
    flexibilityLevel: "flex",
    shiftCompatible: true,
    nutritionBlueprintId: "shift_clock",
    mealStructure: "snack_forward",
    tags: ["shift", "cut"],
  },
  {
    id: "shift_work_structure_growth",
    nameFi: "Vuorotyö — kasvu",
    nameEn: "Shift work — growth",
    goal: "build_muscle",
    mealsPerDay: 4,
    rhythmType: "shift_growth",
    shortDescriptionFi: "Proteiinia ennen ja jälkeen vuoron.",
    shortDescriptionEn: "Protein before and after shifts.",
    idealForFi: "Kun treeni ja vuoro vuorottelevat.",
    idealForEn: "When training and shifts alternate.",
    styleTag: "vuoro",
    proteinBias: "very_high",
    flexibilityLevel: "flex",
    shiftCompatible: true,
    nutritionBlueprintId: "train_vs_rest",
    mealStructure: "snack_forward",
    tags: ["shift", "growth"],
  },
  {
    id: "social_flex_cut",
    nameFi: "Sosiaalinen — kevennys",
    nameEn: "Social — cut",
    goal: "lose_weight",
    mealsPerDay: 4,
    rhythmType: "social_cut",
    shortDescriptionFi: "Tapahtumat mukana, proteiinipainotus säilyy.",
    shortDescriptionEn: "Events included, protein focus stays.",
    idealForFi: "Kun syöt usein ulkona mutta haluat linjaa.",
    idealForEn: "When you eat out often but want a line.",
    styleTag: "joustava",
    proteinBias: "high",
    flexibilityLevel: "flex",
    shiftCompatible: true,
    nutritionBlueprintId: "event_balance",
    mealStructure: "snack_forward",
    tags: ["social", "cut"],
  },
  {
    id: "social_flex_fitness",
    nameFi: "Sosiaalinen — yleiskunto",
    nameEn: "Social — fitness",
    goal: "improve_fitness",
    mealsPerDay: 4,
    rhythmType: "social_fitness",
    shortDescriptionFi: "Joustoa ilman että päivä karkaa.",
    shortDescriptionEn: "Flex without the day running away.",
    idealForFi: "Kun arki ja treffit sekoittuvat.",
    idealForEn: "When life and plans mix.",
    styleTag: "joustava",
    proteinBias: "standard",
    flexibilityLevel: "flex",
    shiftCompatible: true,
    nutritionBlueprintId: "event_balance",
    mealStructure: "snack_forward",
    tags: ["social", "fitness"],
  },
  {
    id: "high_protein_recomp",
    nameFi: "Korkea proteiini — recomp",
    nameEn: "High protein — recomp",
    goal: "lose_weight",
    mealsPerDay: 4,
    rhythmType: "recomp",
    shortDescriptionFi: "Proteiini kantaa, energia hallittu.",
    shortDescriptionEn: "Protein carries, energy controlled.",
    idealForFi: "Kun kiristät mutta säilytät voimaa.",
    idealForEn: "When you tighten but keep strength.",
    styleTag: "cut",
    proteinBias: "very_high",
    flexibilityLevel: "balanced",
    shiftCompatible: true,
    nutritionBlueprintId: "train_vs_rest",
    mealStructure: "snack_forward",
    tags: ["recomp", "high_protein"],
  },
  {
    id: "recovery_day_light",
    nameFi: "Kevyt palautuspäivä",
    nameEn: "Light recovery day",
    goal: "any",
    mealsPerDay: 3,
    rhythmType: "recovery_light",
    shortDescriptionFi: "Kevyt volyymi, helposti sulava.",
    shortDescriptionEn: "Light volume, easy to digest.",
    idealForFi: "Kun viikko on ollut raskas.",
    idealForEn: "When the week has been heavy.",
    styleTag: "palautus",
    proteinBias: "standard",
    flexibilityLevel: "flex",
    shiftCompatible: true,
    nutritionBlueprintId: "easy_daily",
    mealStructure: "three_meals",
    tags: ["recovery", "light"],
  },
  {
    id: "weekend_flexible",
    nameFi: "Viikonloppujoustava",
    nameEn: "Weekend flexible",
    goal: "any",
    mealsPerDay: 4,
    rhythmType: "weekend_flex",
    shortDescriptionFi: "Arki tiukempi, viikonloppu hengittää.",
    shortDescriptionEn: "Weekday tighter, weekend breathes.",
    idealForFi: "Kun haluat tilaa perjantai–sununtai.",
    idealForEn: "When you want room on Fri–Sun.",
    styleTag: "joustava",
    proteinBias: "standard",
    flexibilityLevel: "flex",
    shiftCompatible: true,
    nutritionBlueprintId: "event_balance",
    mealStructure: "snack_forward",
    tags: ["weekend", "flex"],
  },
  {
    id: "coaching_fat_loss",
    nameFi: "Rasvanpoltto",
    nameEn: "Fat loss",
    goal: "any",
    mealsPerDay: 4,
    rhythmType: "cut",
    shortDescriptionFi: "Proteiini kantaa, energia maltillisesti.",
    shortDescriptionEn: "Protein leads; energy stays controlled.",
    idealForFi: "Kun haluat keventää ja pitää nälkä kurissa.",
    idealForEn: "When you want to lean out and manage hunger.",
    styleTag: "poltto",
    proteinBias: "very_high",
    flexibilityLevel: "balanced",
    shiftCompatible: true,
    nutritionBlueprintId: "light_cut_meal",
    mealStructure: "lighter_evening",
    weeklyRhythmFi:
      "Neljä ateriaa, sama runko arkena. Treenipäivä: välipala ennen tai jälkeen.",
    weeklyRhythmEn:
      "Four meals, same weekday frame. Training day: snack before or after.",
    exampleDayFi:
      "Aamiainen: proteiini + kuitu. Lounas: lämmin lautanen. Välipala: rahka tai jogurtti. Illallinen: proteiini + kasvikset.",
    exampleDayEn:
      "Breakfast: protein + fiber. Lunch: warm plate. Snack: quark or yogurt. Dinner: protein + vegetables.",
    tags: ["coaching", "core"],
  },
  {
    id: "coaching_lean_bulk",
    nameFi: "Lean bulk",
    nameEn: "Lean bulk",
    goal: "any",
    mealsPerDay: 4,
    rhythmType: "growth",
    shortDescriptionFi: "Hieman ylijäämää, proteiini kohillaan.",
    shortDescriptionEn: "Slight surplus with protein on point.",
    idealForFi: "Kun rakennat lihasta ilman turhaa rasvaa.",
    idealForEn: "When you build muscle without extra fluff.",
    styleTag: "bulk",
    proteinBias: "very_high",
    flexibilityLevel: "structured",
    shiftCompatible: true,
    nutritionBlueprintId: "muscle_fuel",
    mealStructure: "snack_forward",
    weeklyRhythmFi: "Treenipäivinä hiilarit treenin ympärille; lepopäivinä tasaisemmin.",
    weeklyRhythmEn: "Training days: carbs around sessions; rest days steadier.",
    exampleDayFi:
      "Aamiainen täyteläs. Lounas proteiini + hiilarit. Ennen treeniä kevyt välipala. Illalla proteiini + kasvikset.",
    exampleDayEn:
      "Hearty breakfast. Lunch: protein + carbs. Light pre-workout snack. Evening: protein + veg.",
    tags: ["coaching", "core"],
  },
  {
    id: "coaching_maintenance",
    nameFi: "Ylläpito",
    nameEn: "Maintenance",
    goal: "any",
    mealsPerDay: 4,
    rhythmType: "four_normal",
    shortDescriptionFi: "Tasainen energia, joustoa viikkoon.",
    shortDescriptionEn: "Steady energy with room to flex.",
    idealForFi: "Kun paino ja suorituskyky pysyvät suunnilleen samana.",
    idealForEn: "When weight and performance stay roughly stable.",
    styleTag: "taso",
    proteinBias: "high",
    flexibilityLevel: "balanced",
    shiftCompatible: true,
    nutritionBlueprintId: "steady_meals",
    mealStructure: "snack_forward",
    weeklyRhythmFi: "Neljä ateriaa; viikonloppuun voi jättää yhden joustavan aterian.",
    weeklyRhythmEn: "Four meals; leave one flexible meal on the weekend if needed.",
    exampleDayFi:
      "Aamiainen, lounas, välipala, illallinen — proteiinia jokaisessa.",
    exampleDayEn:
      "Breakfast, lunch, snack, dinner — protein in each.",
    tags: ["coaching", "core"],
  },
  {
    id: "coaching_easy_start",
    nameFi: "Helppo aloitus",
    nameEn: "Easy start",
    goal: "any",
    mealsPerDay: 3,
    rhythmType: "three_easy",
    shortDescriptionFi: "Kolme selkeää ateriaa — ei välipalakiirettä.",
    shortDescriptionEn: "Three clear meals — no snack rush.",
    idealForFi: "Kun haluat yksinkertaisen ateriapohjan ensin.",
    idealForEn: "When you want a simple meal frame first.",
    styleTag: "aloitus",
    proteinBias: "standard",
    flexibilityLevel: "balanced",
    shiftCompatible: true,
    nutritionBlueprintId: "easy_daily",
    mealStructure: "three_meals",
    weeklyRhythmFi: "Aamiainen–lounas–illallinen; treenipäivänä välipala voidaan lisätä.",
    weeklyRhythmEn: "Breakfast–lunch–dinner; add a snack on training days if needed.",
    exampleDayFi:
      "Aamiainen: proteiini + hedelmä/kaura. Lounas: lämmin ruoka. Illallinen: proteiini + kasvikset.",
    exampleDayEn:
      "Breakfast: protein + fruit/oats. Lunch: warm meal. Dinner: protein + vegetables.",
    tags: ["coaching", "core", "mealplan"],
  },
];

/** Neljä päävalintaa — ruokavalinnat-näkymän ydin. */
export const NUTRITION_COACHING_CORE_IDS: readonly string[] = [
  "coaching_fat_loss",
  "coaching_lean_bulk",
  "coaching_maintenance",
  "coaching_easy_start",
];

export function listNutritionCoachingCore(
  goal: Goal | "all",
): NutritionLibraryEntry[] {
  const byId = new Map(NUTRITION_LIBRARY.map((e) => [e.id, e]));
  const out: NutritionLibraryEntry[] = [];
  for (const id of NUTRITION_COACHING_CORE_IDS) {
    const e = byId.get(id);
    if (!e) continue;
    if (goal === "all" || e.goal === "any" || e.goal === goal) out.push(e);
  }
  return out;
}

export function getNutritionLibraryEntry(id: string): NutritionLibraryEntry | undefined {
  return NUTRITION_LIBRARY.find((e) => e.id === id);
}

function matchesGoal(e: NutritionLibraryEntry, g: Goal): boolean {
  return e.goal === "any" || e.goal === g;
}

export function listNutritionForGoal(goal: Goal): NutritionLibraryEntry[] {
  return NUTRITION_LIBRARY.filter((e) => matchesGoal(e, goal));
}

export function recommendNutritionForProfile(profile: OnboardingAnswers): NutritionLibraryEntry {
  const resolved = resolveProgramFromProfile(profile);
  const pool = listNutritionForGoal(profile.goal);
  const hit = pool.find((e) => e.nutritionBlueprintId === resolved.nutritionBlueprintId);
  if (hit) return hit;
  return pool[0] ?? NUTRITION_LIBRARY[0];
}

export function alternativeNutritionForProfile(
  profile: OnboardingAnswers,
  recommended: NutritionLibraryEntry,
  limit = 5,
): NutritionLibraryEntry[] {
  return listNutritionForGoal(profile.goal)
    .filter((e) => e.id !== recommended.id)
    .slice(0, limit);
}

export function applyNutritionLibraryEntry(
  entryId: string,
): Partial<OnboardingAnswers> {
  const entry = getNutritionLibraryEntry(entryId);
  if (!entry) return {};
  return {
    selectedNutritionLibraryId: entry.id,
    nutritionBlueprintId: entry.nutritionBlueprintId,
    mealStructure: entry.mealStructure,
  };
}
