/**
 * Laajennus V1 — oma data, kategoriat ja tagit.
 */
import type { FoodLibraryItem } from "@/types/foodLibrary";

export const FOOD_SEARCH_EXTRA_BATCH2: FoodLibraryItem[] = [
  { id: "fl_b2_01", nameFi: "Overnight kaura + marjat", nameEn: "Overnight oats + berries", kcal: 360, proteinG: 16, carbsG: 52, fatG: 10, tags: ["breakfast", "batch", "office_friendly"], category: "breakfast", goalFit: ["improve_fitness", "lose_weight"], proteinLevel: "mid", prepStyle: "batch", mealSlot: "breakfast", cheap: true, shiftFriendly: true, whyFi: "Illalla teet, aamulla valmis.", whyEn: "Prep eve, ready AM." },
  { id: "fl_b2_02", nameFi: "Cottage bowl + hunaja + marjat", nameEn: "Cottage bowl + honey + berries", kcal: 280, proteinG: 28, carbsG: 28, fatG: 6, tags: ["high_protein", "snack", "quick"], category: "breakfast", goalFit: ["build_muscle", "lose_weight"], proteinLevel: "high", prepStyle: "easy", mealSlot: "breakfast", cheap: true, shiftFriendly: true, whyFi: "Nopea proteiinipommi.", whyEn: "Fast protein hit." },
  { id: "fl_b2_03", nameFi: "Kefir + marjat + pähkinä", nameEn: "Kefir + berries + nuts", kcal: 240, proteinG: 12, carbsG: 22, fatG: 12, tags: ["snack", "easy"], category: "snack", goalFit: ["improve_fitness"], proteinLevel: "mid", prepStyle: "easy", mealSlot: "snack", cheap: true, shiftFriendly: true, whyFi: "Kevyt väli, hyvä suolisto.", whyEn: "Light gap, gut-friendly." },
  { id: "fl_b2_04", nameFi: "Proteiinivanukas + kaneli", nameEn: "Protein pudding + cinnamon", kcal: 190, proteinG: 20, carbsG: 18, fatG: 4, tags: ["high_protein", "snack"], category: "snack", goalFit: ["build_muscle", "lose_weight"], proteinLevel: "high", prepStyle: "easy", mealSlot: "snack", cheap: true, shiftFriendly: true, whyFi: "Makea ilman sokeripiikkiä.", whyEn: "Sweet without a sugar spike." },
  { id: "fl_b2_05", nameFi: "Kana-caesar kevyt (jogurttikastike)", nameEn: "Light chicken Caesar (yogurt dressing)", kcal: 420, proteinG: 42, carbsG: 22, fatG: 18, tags: ["meal", "high_protein"], category: "meal", goalFit: ["lose_weight", "build_muscle"], proteinLevel: "high", prepStyle: "normal", mealSlot: "lunch", cheap: true, shiftFriendly: true, whyFi: "Klassikko, vähemmän öljyä.", whyEn: "Classic, less oil." },
  { id: "fl_b2_06", nameFi: "Jauhelihawokki + nuudeli", nameEn: "Minced meat wok + noodles", kcal: 580, proteinG: 34, carbsG: 62, fatG: 22, tags: ["meal", "quick"], category: "meal", goalFit: ["build_muscle", "improve_fitness"], proteinLevel: "mid", prepStyle: "quick", mealSlot: "dinner", cheap: true, shiftFriendly: true, whyFi: "Yksi pannu, nopea.", whyEn: "One pan, fast." },
  { id: "fl_b2_07", nameFi: "Kanariisivuoka", nameEn: "Chicken rice bake", kcal: 560, proteinG: 40, carbsG: 58, fatG: 18, tags: ["meal", "batch"], category: "meal", goalFit: ["build_muscle"], proteinLevel: "high", prepStyle: "batch", mealSlot: "dinner", cheap: true, shiftFriendly: true, whyFi: "Batchista monta päivää.", whyEn: "Batch for several days." },
  { id: "fl_b2_08", nameFi: "Lohikeitto kevyt", nameEn: "Light salmon soup", kcal: 380, proteinG: 28, carbsG: 32, fatG: 16, tags: ["meal"], category: "meal", goalFit: ["lose_weight", "improve_fitness"], proteinLevel: "high", prepStyle: "normal", mealSlot: "lunch", cheap: false, shiftFriendly: true, whyFi: "Täyttävä mutta kevyt.", whyEn: "Filling yet light." },
  { id: "fl_b2_09", nameFi: "Tofu-riisibowl", nameEn: "Tofu rice bowl", kcal: 490, proteinG: 22, carbsG: 68, fatG: 14, tags: ["meal", "cheap"], category: "meal", goalFit: ["improve_fitness", "lose_weight"], proteinLevel: "mid", prepStyle: "quick", mealSlot: "lunch", cheap: true, shiftFriendly: true, whyFi: "Kasvispainotteinen proteiini.", whyEn: "Plant-forward protein." },
  { id: "fl_b2_10", nameFi: "Chili con carne + riisi", nameEn: "Chili con carne + rice", kcal: 590, proteinG: 36, carbsG: 62, fatG: 22, tags: ["meal", "batch"], category: "meal", goalFit: ["build_muscle", "improve_fitness"], proteinLevel: "mid", prepStyle: "batch", mealSlot: "dinner", cheap: true, shiftFriendly: true, whyFi: "Isosta padasta useampi ateria.", whyEn: "Big pot → multiple meals." },
  { id: "fl_b2_11", nameFi: "Raejuusto + kurkku + öljy", nameEn: "Cottage + cucumber + oil", kcal: 210, proteinG: 24, carbsG: 8, fatG: 10, tags: ["snack", "high_protein", "no_cook"], category: "snack", goalFit: ["lose_weight", "build_muscle"], proteinLevel: "high", prepStyle: "easy", mealSlot: "snack", cheap: true, shiftFriendly: true, whyFi: "Ei lämmitystä, korkea P.", whyEn: "No heat, high P." },
  { id: "fl_b2_12", nameFi: "Rahka + hunaja + pähkinä", nameEn: "Quark + honey + nuts", kcal: 290, proteinG: 22, carbsG: 28, fatG: 10, tags: ["snack"], category: "snack", goalFit: ["improve_fitness"], proteinLevel: "mid", prepStyle: "easy", mealSlot: "snack", cheap: true, shiftFriendly: true, whyFi: "Nopea makea väli.", whyEn: "Quick sweet gap." },
  { id: "fl_b2_13", nameFi: "Proteiinijuoma + banaani", nameEn: "Protein drink + banana", kcal: 260, proteinG: 24, carbsG: 32, fatG: 4, tags: ["postworkout", "quick"], category: "postworkout", goalFit: ["build_muscle"], proteinLevel: "high", prepStyle: "quick", mealSlot: "postworkout", cheap: false, shiftFriendly: true, whyFi: "Hiilarit + proteiini treenin jälkeen.", whyEn: "Carbs + protein post-workout." },
  { id: "fl_b2_14", nameFi: "Riisikakut + kalkkuna + kurkku", nameEn: "Rice cakes + turkey + cucumber", kcal: 270, proteinG: 22, carbsG: 30, fatG: 8, tags: ["snack", "office_friendly"], category: "snack", goalFit: ["lose_weight"], proteinLevel: "mid", prepStyle: "easy", mealSlot: "snack", cheap: true, shiftFriendly: true, whyFi: "Kevyt toimistolounas.", whyEn: "Light office lunch." },
  { id: "fl_b2_15", nameFi: "Smoothie (marja + hera)", nameEn: "Berry whey smoothie", kcal: 300, proteinG: 28, carbsG: 36, fatG: 6, tags: ["breakfast", "quick", "postworkout"], category: "breakfast", goalFit: ["build_muscle", "improve_fitness"], proteinLevel: "high", prepStyle: "quick", mealSlot: "breakfast", cheap: true, shiftFriendly: true, whyFi: "Juotava aamiainen.", whyEn: "Drinkable breakfast." },
  { id: "fl_b2_16", nameFi: "Uunimunakas + feta + kasvikset", nameEn: "Baked omelette + feta + veg", kcal: 400, proteinG: 28, carbsG: 14, fatG: 26, tags: ["breakfast", "batch"], category: "breakfast", goalFit: ["improve_fitness", "lose_weight"], proteinLevel: "high", prepStyle: "batch", mealSlot: "breakfast", cheap: true, shiftFriendly: true, whyFi: "Uunista monta annosta.", whyEn: "Oven → multiple portions." },
  { id: "fl_b2_17", nameFi: "Täysjyvä pasta + tonnikala + tomaatti", nameEn: "Wholewheat pasta + tuna + tomato", kcal: 540, proteinG: 36, carbsG: 72, fatG: 14, tags: ["meal", "cheap"], category: "meal", goalFit: ["improve_fitness", "build_muscle"], proteinLevel: "mid", prepStyle: "normal", mealSlot: "dinner", cheap: true, shiftFriendly: true, whyFi: "Halpa kaapin antimista.", whyEn: "Budget pantry meal." },
  { id: "fl_b2_18", nameFi: "Paistettu tofu + kasvis + riisi", nameEn: "Fried tofu + veg + rice", kcal: 470, proteinG: 20, carbsG: 68, fatG: 14, tags: ["meal"], category: "meal", goalFit: ["lose_weight", "improve_fitness"], proteinLevel: "mid", prepStyle: "quick", mealSlot: "lunch", cheap: true, shiftFriendly: true, whyFi: "Kasvispainotteinen lounas.", whyEn: "Plant-forward lunch." },
  { id: "fl_b2_19", nameFi: "Kalkkuna + bataatti + parsakaali", nameEn: "Turkey + sweet potato + broccoli", kcal: 500, proteinG: 44, carbsG: 48, fatG: 12, tags: ["meal", "high_protein"], category: "meal", goalFit: ["build_muscle", "lose_weight"], proteinLevel: "high", prepStyle: "normal", mealSlot: "dinner", cheap: true, shiftFriendly: true, whyFi: "Tasapainoinen makrojakautuma.", whyEn: "Balanced macro split." },
  { id: "fl_b2_20", nameFi: "Proteiinipatukka + omena", nameEn: "Protein bar + apple", kcal: 280, proteinG: 18, carbsG: 38, fatG: 8, tags: ["snack", "postworkout"], category: "snack", goalFit: ["improve_fitness"], proteinLevel: "mid", prepStyle: "quick", mealSlot: "snack", cheap: false, shiftFriendly: true, whyFi: "Taskussa mukana.", whyEn: "Pocket carry." },
  { id: "fl_b2_21", nameFi: "Kreikkalainen jogurtti + granola + marjat", nameEn: "Greek yogurt + granola + berries", kcal: 380, proteinG: 20, carbsG: 48, fatG: 12, tags: ["breakfast"], category: "breakfast", goalFit: ["improve_fitness"], proteinLevel: "mid", prepStyle: "easy", mealSlot: "breakfast", cheap: true, shiftFriendly: true, whyFi: "Klassinen aamupala.", whyEn: "Classic breakfast." },
  { id: "fl_b2_22", nameFi: "Kasvissosekeitto + juustoleipä", nameEn: "Veg soup + cheese bread", kcal: 410, proteinG: 16, carbsG: 52, fatG: 16, tags: ["meal", "busy"], category: "meal", goalFit: ["improve_fitness", "lose_weight"], proteinLevel: "low", prepStyle: "batch", mealSlot: "lunch", cheap: true, shiftFriendly: true, whyFi: "Lämmittävä ja edullinen.", whyEn: "Warming and budget." },
  { id: "fl_b2_23", nameFi: "Paistettu kana + couscous + salaatti", nameEn: "Grilled chicken + couscous + salad", kcal: 510, proteinG: 42, carbsG: 52, fatG: 14, tags: ["meal"], category: "meal", goalFit: ["build_muscle"], proteinLevel: "high", prepStyle: "normal", mealSlot: "lunch", cheap: false, shiftFriendly: true, whyFi: "Täyttävä lounas.", whyEn: "Filling lunch." },
  { id: "fl_b2_24", nameFi: "Munakasari + täysjyväleipä", nameEn: "Scramble + wholegrain bread", kcal: 430, proteinG: 26, carbsG: 38, fatG: 20, tags: ["breakfast"], category: "breakfast", goalFit: ["improve_fitness", "build_muscle"], proteinLevel: "mid", prepStyle: "easy", mealSlot: "breakfast", cheap: true, shiftFriendly: true, whyFi: "Nopea aamuproteiini.", whyEn: "Fast AM protein." },
  { id: "fl_b2_25", nameFi: "Riisipuuro + marjat + proteiinijauhe", nameEn: "Rice porridge + berries + protein", kcal: 390, proteinG: 26, carbsG: 56, fatG: 8, tags: ["breakfast", "muscle_gain"], category: "breakfast", goalFit: ["build_muscle"], proteinLevel: "high", prepStyle: "easy", mealSlot: "breakfast", cheap: true, shiftFriendly: true, whyFi: "Kaura vaihtoehto kauralle.", whyEn: "Oats alternative bowl." },
  { id: "fl_b2_26", nameFi: "Nakkikeitto + ruisleipä", nameEn: "Sausage soup + rye bread", kcal: 460, proteinG: 20, carbsG: 46, fatG: 22, tags: ["meal", "cheap"], category: "meal", goalFit: ["improve_fitness"], proteinLevel: "low", prepStyle: "quick", mealSlot: "lunch", cheap: true, shiftFriendly: true, whyFi: "Perusarkiruoka.", whyEn: "Comfort staple." },
  { id: "fl_b2_27", nameFi: "Poke-kulho (kasvis)", nameEn: "Veggie poke bowl", kcal: 440, proteinG: 18, carbsG: 72, fatG: 10, tags: ["meal"], category: "meal", goalFit: ["improve_fitness", "lose_weight"], proteinLevel: "mid", prepStyle: "quick", mealSlot: "lunch", cheap: false, shiftFriendly: true, whyFi: "Värikäs lautanen.", whyEn: "Colorful bowl." },
  { id: "fl_b2_28", nameFi: "Hedelmä + pähkinät + proteiinijuoma", nameEn: "Fruit + nuts + protein shake", kcal: 310, proteinG: 24, carbsG: 34, fatG: 10, tags: ["snack", "postworkout"], category: "snack", goalFit: ["build_muscle"], proteinLevel: "mid", prepStyle: "quick", mealSlot: "snack", cheap: true, shiftFriendly: true, whyFi: "Nopea palautus.", whyEn: "Quick recovery." },
];
