/**
 * Oma tuotekatalogi — arvioidut hinnat, ei reaaliaikaista kauppadataa.
 * Myöhemmin: viralliset integraatiot / käyttäjän tuotteet.
 */
import type { GroceryProduct, StoreId } from "@/types/grocery";

const S = {
  store_a: "store_a",
  store_b: "store_b",
  store_c: "store_c",
} as const satisfies Record<string, StoreId>;

/** Arvioitu hinta / myyntiyksikkö (eur) — paikallinen arvio */
function p(
  partial: Omit<GroceryProduct, "id"> & { idSuffix: string; store: StoreId },
): GroceryProduct {
  const id = `${partial.store}_${partial.idSuffix}`;
  const { idSuffix, store, ...rest } = partial;
  return {
    ...rest,
    id,
    storeId: store,
  };
}

/** Perusvalikoima: sama logiinen tuote kolmessa hinta-/kauppakerroksessa */
export const PRODUCT_CATALOG: GroceryProduct[] = [
  p({
    store: S.store_a,
    idSuffix: "chicken_600",
    nameFi: "Broilerin filee",
    nameEn: "Chicken breast fillet",
    category: "protein",
    unit: "g",
    packSize: 600,
    estimatedPrice: 4.99,
    barcode: "6410402001234",
    tags: ["chicken_breast"],
    substitutes: ["kalkkuna_filee", "tofu_luomu"],
  }),
  p({
    store: S.store_b,
    idSuffix: "chicken_600",
    nameFi: "Broilerin filee",
    nameEn: "Chicken breast fillet",
    category: "protein",
    unit: "g",
    packSize: 600,
    estimatedPrice: 6.49,
    tags: ["chicken_breast"],
    substitutes: ["kalkkuna_filee", "tofu_luomu"],
  }),
  p({
    store: S.store_c,
    idSuffix: "chicken_600",
    nameFi: "Broilerin filee (premium)",
    nameEn: "Chicken breast (premium)",
    category: "protein",
    unit: "g",
    packSize: 600,
    estimatedPrice: 8.9,
    tags: ["chicken_breast"],
    substitutes: ["kalkkuna_filee", "tofu_luomu"],
  }),

  p({
    store: S.store_a,
    idSuffix: "mince_400",
    nameFi: "Naudan jauheliha 17%",
    nameEn: "Beef mince 17%",
    category: "protein",
    unit: "g",
    packSize: 400,
    estimatedPrice: 5.49,
    tags: ["beef_mince"],
    substitutes: ["chicken_breast", "kasvis_fj"],
  }),
  p({
    store: S.store_b,
    idSuffix: "mince_400",
    nameFi: "Naudan jauheliha 17%",
    nameEn: "Beef mince 17%",
    category: "protein",
    unit: "g",
    packSize: 400,
    estimatedPrice: 6.99,
    tags: ["beef_mince"],
    substitutes: ["chicken_breast", "kasvis_fj"],
  }),
  p({
    store: S.store_c,
    idSuffix: "mince_400",
    nameFi: "Naudan jauheliha (luomu)",
    nameEn: "Organic beef mince",
    category: "protein",
    unit: "g",
    packSize: 400,
    estimatedPrice: 9.5,
    tags: ["beef_mince"],
    substitutes: ["chicken_breast", "kasvis_fj"],
  }),

  p({
    store: S.store_a,
    idSuffix: "salmon_250",
    nameFi: "Lohifilé",
    nameEn: "Salmon fillet",
    category: "protein",
    unit: "g",
    packSize: 250,
    estimatedPrice: 7.99,
    tags: ["salmon"],
    substitutes: ["chicken_breast", "kala_muu"],
  }),
  p({
    store: S.store_b,
    idSuffix: "salmon_250",
    nameFi: "Lohifilé",
    nameEn: "Salmon fillet",
    category: "protein",
    unit: "g",
    packSize: 250,
    estimatedPrice: 9.49,
    tags: ["salmon"],
    substitutes: ["chicken_breast", "kala_muu"],
  }),
  p({
    store: S.store_c,
    idSuffix: "salmon_250",
    nameFi: "Lohifilé",
    nameEn: "Salmon fillet",
    category: "protein",
    unit: "g",
    packSize: 250,
    estimatedPrice: 11.9,
    tags: ["salmon"],
    substitutes: ["chicken_breast", "kala_muu"],
  }),

  p({
    store: S.store_a,
    idSuffix: "eggs_12",
    nameFi: "Kananmunat 12 kpl",
    nameEn: "Eggs 12 pcs",
    category: "protein",
    unit: "piece",
    packSize: 12,
    estimatedPrice: 2.99,
    tags: ["eggs"],
    substitutes: [],
  }),
  p({
    store: S.store_b,
    idSuffix: "eggs_12",
    nameFi: "Kananmunat 12 kpl",
    nameEn: "Eggs 12 pcs",
    category: "protein",
    unit: "piece",
    packSize: 12,
    estimatedPrice: 3.49,
    tags: ["eggs"],
    substitutes: [],
  }),
  p({
    store: S.store_c,
    idSuffix: "eggs_12",
    nameFi: "Kananmunat (vapaan)",
    nameEn: "Free-range eggs 12",
    category: "protein",
    unit: "piece",
    packSize: 12,
    estimatedPrice: 4.49,
    tags: ["eggs"],
    substitutes: [],
  }),

  p({
    store: S.store_a,
    idSuffix: "cottage_200",
    nameFi: "Raejuusto 200 g",
    nameEn: "Cottage cheese 200 g",
    category: "dairy",
    unit: "g",
    packSize: 200,
    estimatedPrice: 1.29,
    tags: ["cottage_cheese"],
    substitutes: ["rahka", "greek_yogurt"],
  }),
  p({
    store: S.store_b,
    idSuffix: "cottage_200",
    nameFi: "Raejuusto 200 g",
    nameEn: "Cottage cheese 200 g",
    category: "dairy",
    unit: "g",
    packSize: 200,
    estimatedPrice: 1.69,
    tags: ["cottage_cheese"],
    substitutes: ["rahka", "greek_yogurt"],
  }),
  p({
    store: S.store_c,
    idSuffix: "cottage_200",
    nameFi: "Raejuusto",
    nameEn: "Cottage cheese",
    category: "dairy",
    unit: "g",
    packSize: 200,
    estimatedPrice: 2.29,
    tags: ["cottage_cheese"],
    substitutes: ["rahka", "greek_yogurt"],
  }),

  p({
    store: S.store_a,
    idSuffix: "quark_400",
    nameFi: "Maitorahka 400 g",
    nameEn: "Quark 400 g",
    category: "dairy",
    unit: "g",
    packSize: 400,
    estimatedPrice: 1.89,
    tags: ["quark"],
    substitutes: ["cottage_cheese", "greek_yogurt"],
  }),
  p({
    store: S.store_b,
    idSuffix: "quark_400",
    nameFi: "Maitorahka 400 g",
    nameEn: "Quark 400 g",
    category: "dairy",
    unit: "g",
    packSize: 400,
    estimatedPrice: 2.29,
    tags: ["quark"],
    substitutes: ["cottage_cheese", "greek_yogurt"],
  }),
  p({
    store: S.store_c,
    idSuffix: "quark_400",
    nameFi: "Proteiinirahka",
    nameEn: "Protein quark",
    category: "dairy",
    unit: "g",
    packSize: 400,
    estimatedPrice: 2.99,
    tags: ["quark"],
    substitutes: ["cottage_cheese", "greek_yogurt"],
  }),

  p({
    store: S.store_a,
    idSuffix: "rice_1kg",
    nameFi: "Riisi 1 kg",
    nameEn: "Rice 1 kg",
    category: "carb",
    unit: "kg",
    packSize: 1000,
    estimatedPrice: 2.49,
    tags: ["rice"],
    substitutes: ["pasta", "peruna"],
  }),
  p({
    store: S.store_b,
    idSuffix: "rice_1kg",
    nameFi: "Riisi 1 kg",
    nameEn: "Rice 1 kg",
    category: "carb",
    packSize: 1000,
    unit: "kg",
    estimatedPrice: 2.99,
    tags: ["rice"],
    substitutes: ["pasta", "peruna"],
  }),
  p({
    store: S.store_c,
    idSuffix: "rice_1kg",
    nameFi: "Basmatiriisi 1 kg",
    nameEn: "Basmati rice 1 kg",
    category: "carb",
    unit: "kg",
    packSize: 1000,
    estimatedPrice: 3.99,
    tags: ["rice"],
    substitutes: ["pasta", "peruna"],
  }),

  p({
    store: S.store_a,
    idSuffix: "oats_1kg",
    nameFi: "Kaurahiutaleet 1 kg",
    nameEn: "Oats 1 kg",
    category: "carb",
    unit: "kg",
    packSize: 1000,
    estimatedPrice: 1.99,
    tags: ["oats"],
    substitutes: ["muesli"],
  }),
  p({
    store: S.store_b,
    idSuffix: "oats_1kg",
    nameFi: "Kaurahiutaleet 1 kg",
    nameEn: "Oats 1 kg",
    category: "carb",
    unit: "kg",
    packSize: 1000,
    estimatedPrice: 2.49,
    tags: ["oats"],
    substitutes: ["muesli"],
  }),
  p({
    store: S.store_c,
    idSuffix: "oats_1kg",
    nameFi: "Gluteenittomat kaurahiutaleet",
    nameEn: "Gluten-free oats 1 kg",
    category: "carb",
    unit: "kg",
    packSize: 1000,
    estimatedPrice: 3.49,
    tags: ["oats"],
    substitutes: ["muesli"],
  }),

  p({
    store: S.store_a,
    idSuffix: "potato_2kg",
    nameFi: "Peruna 2 kg",
    nameEn: "Potatoes 2 kg",
    category: "carb",
    unit: "kg",
    packSize: 2000,
    estimatedPrice: 2.99,
    tags: ["potato"],
    substitutes: ["rice", "pasta"],
  }),
  p({
    store: S.store_b,
    idSuffix: "potato_2kg",
    nameFi: "Peruna 2 kg",
    nameEn: "Potatoes 2 kg",
    category: "carb",
    unit: "kg",
    packSize: 2000,
    estimatedPrice: 3.49,
    tags: ["potato"],
    substitutes: ["rice", "pasta"],
  }),
  p({
    store: S.store_c,
    idSuffix: "potato_2kg",
    nameFi: "Uusi peruna 1,5 kg",
    nameEn: "New potatoes 1.5 kg",
    category: "carb",
    unit: "kg",
    packSize: 1500,
    estimatedPrice: 4.49,
    tags: ["potato"],
    substitutes: ["rice", "pasta"],
  }),

  p({
    store: S.store_a,
    idSuffix: "pasta_500",
    nameFi: "Täysjyväpasta 500 g",
    nameEn: "Whole wheat pasta 500 g",
    category: "carb",
    unit: "g",
    packSize: 500,
    estimatedPrice: 1.49,
    tags: ["pasta"],
    substitutes: ["rice", "peruna"],
  }),
  p({
    store: S.store_b,
    idSuffix: "pasta_500",
    nameFi: "Täysjyväpasta 500 g",
    nameEn: "Whole wheat pasta 500 g",
    category: "carb",
    unit: "g",
    packSize: 500,
    estimatedPrice: 1.99,
    tags: ["pasta"],
    substitutes: ["rice", "peruna"],
  }),
  p({
    store: S.store_c,
    idSuffix: "pasta_500",
    nameFi: "Pasta (durum)",
    nameEn: "Durum pasta 500 g",
    category: "carb",
    unit: "g",
    packSize: 500,
    estimatedPrice: 2.79,
    tags: ["pasta"],
    substitutes: ["rice", "peruna"],
  }),

  p({
    store: S.store_a,
    idSuffix: "oil_500",
    nameFi: "Oliiviöljy 500 ml",
    nameEn: "Olive oil 500 ml",
    category: "fat",
    unit: "ml",
    packSize: 500,
    estimatedPrice: 5.99,
    tags: ["olive_oil"],
    substitutes: ["rypsi"],
  }),
  p({
    store: S.store_b,
    idSuffix: "oil_500",
    nameFi: "Oliiviöljy 500 ml",
    nameEn: "Olive oil 500 ml",
    category: "fat",
    unit: "ml",
    packSize: 500,
    estimatedPrice: 6.99,
    tags: ["olive_oil"],
    substitutes: ["rypsi"],
  }),
  p({
    store: S.store_c,
    idSuffix: "oil_500",
    nameFi: "Extra virgin oliiviöljy",
    nameEn: "Extra virgin olive oil 500 ml",
    category: "fat",
    unit: "ml",
    packSize: 500,
    estimatedPrice: 9.9,
    tags: ["olive_oil"],
    substitutes: ["rypsi"],
  }),

  p({
    store: S.store_a,
    idSuffix: "nuts_200",
    nameFi: "Sekapähkinät 200 g",
    nameEn: "Mixed nuts 200 g",
    category: "snack",
    unit: "g",
    packSize: 200,
    estimatedPrice: 3.49,
    tags: ["nuts"],
    substitutes: [],
  }),
  p({
    store: S.store_b,
    idSuffix: "nuts_200",
    nameFi: "Sekapähkinät 200 g",
    nameEn: "Mixed nuts 200 g",
    category: "snack",
    unit: "g",
    packSize: 200,
    estimatedPrice: 3.99,
    tags: ["nuts"],
    substitutes: [],
  }),
  p({
    store: S.store_c,
    idSuffix: "nuts_200",
    nameFi: "Pähkinät (premium)",
    nameEn: "Premium nuts 200 g",
    category: "snack",
    unit: "g",
    packSize: 200,
    estimatedPrice: 5.49,
    tags: ["nuts"],
    substitutes: [],
  }),

  p({
    store: S.store_a,
    idSuffix: "veg_frozen_750",
    nameFi: "Pakastekasvikset 750 g",
    nameEn: "Frozen veg mix 750 g",
    category: "vegetable",
    unit: "g",
    packSize: 750,
    estimatedPrice: 2.29,
    tags: ["veg_frozen"],
    substitutes: [],
  }),
  p({
    store: S.store_b,
    idSuffix: "veg_frozen_750",
    nameFi: "Pakastekasvikset 750 g",
    nameEn: "Frozen veg mix 750 g",
    category: "vegetable",
    unit: "g",
    packSize: 750,
    estimatedPrice: 2.79,
    tags: ["veg_frozen"],
    substitutes: [],
  }),
  p({
    store: S.store_c,
    idSuffix: "veg_frozen_750",
    nameFi: "Luomupakaste kasviksia",
    nameEn: "Organic frozen veg 750 g",
    category: "vegetable",
    unit: "g",
    packSize: 750,
    estimatedPrice: 3.99,
    tags: ["veg_frozen"],
    substitutes: [],
  }),

  p({
    store: S.store_a,
    idSuffix: "salad",
    nameFi: "Salaatti 2 kpl",
    nameEn: "Salad greens 2 bags",
    category: "vegetable",
    unit: "pack",
    packSize: 2,
    estimatedPrice: 3.99,
    tags: ["salad_greens"],
    substitutes: [],
  }),
  p({
    store: S.store_b,
    idSuffix: "salad",
    nameFi: "Salaatti 2 kpl",
    nameEn: "Salad greens 2 bags",
    category: "vegetable",
    unit: "pack",
    packSize: 2,
    estimatedPrice: 4.49,
    tags: ["salad_greens"],
    substitutes: [],
  }),
  p({
    store: S.store_c,
    idSuffix: "salad",
    nameFi: "Baby spinach",
    nameEn: "Baby spinach 2 bags",
    category: "vegetable",
    unit: "pack",
    packSize: 2,
    estimatedPrice: 5.9,
    tags: ["salad_greens"],
    substitutes: [],
  }),

  p({
    store: S.store_a,
    idSuffix: "berries_400",
    nameFi: "Marjat 400 g",
    nameEn: "Berries 400 g",
    category: "fruit",
    unit: "g",
    packSize: 400,
    estimatedPrice: 3.99,
    tags: ["berries"],
    substitutes: ["banaani"],
  }),
  p({
    store: S.store_b,
    idSuffix: "berries_400",
    nameFi: "Marjat 400 g",
    nameEn: "Berries 400 g",
    category: "fruit",
    unit: "g",
    packSize: 400,
    estimatedPrice: 4.49,
    tags: ["berries"],
    substitutes: ["banaani"],
  }),
  p({
    store: S.store_c,
    idSuffix: "berries_400",
    nameFi: "Pakastemarjat (luomu)",
    nameEn: "Organic frozen berries 400 g",
    category: "fruit",
    unit: "g",
    packSize: 400,
    estimatedPrice: 5.99,
    tags: ["berries"],
    substitutes: ["banaani"],
  }),

  p({
    store: S.store_a,
    idSuffix: "tofu_250",
    nameFi: "Tofu 250 g",
    nameEn: "Tofu 250 g",
    category: "protein",
    unit: "g",
    packSize: 250,
    estimatedPrice: 2.49,
    tags: ["tofu"],
    substitutes: ["chicken_breast"],
  }),
  p({
    store: S.store_b,
    idSuffix: "tofu_250",
    nameFi: "Tofu 250 g",
    nameEn: "Tofu 250 g",
    category: "protein",
    unit: "g",
    packSize: 250,
    estimatedPrice: 2.99,
    tags: ["tofu"],
    substitutes: ["chicken_breast"],
  }),
  p({
    store: S.store_c,
    idSuffix: "tofu_250",
    nameFi: "Luomutofu",
    nameEn: "Organic tofu 250 g",
    category: "protein",
    unit: "g",
    packSize: 250,
    estimatedPrice: 3.99,
    tags: ["tofu"],
    substitutes: ["chicken_breast"],
  }),
];

export function getProductCatalog(): GroceryProduct[] {
  return PRODUCT_CATALOG;
}

export function productsForIngredientKey(
  catalog: GroceryProduct[],
  ingredientKey: string,
): GroceryProduct[] {
  return catalog.filter((x) => x.tags?.includes(ingredientKey));
}

export function productsForStore(
  catalog: GroceryProduct[],
  storeId: StoreId,
): GroceryProduct[] {
  return catalog.filter((x) => x.storeId === storeId);
}
